### ISSUE TITLE
Doku/Setup

### ISSUE THREAD

**Issue by maze2point0** [KasimirOr/SRRM#1]
Some things I came across:

- [x] where to put the downloaded files from HiDrive?
- [x] the referenced volume to mount in the docker compose file is `- ../PYTHON_SRRM:/home/srrm`, but with the repos actual nae it should be  `- ../SRRM:/home/srrm`
- [x] when running `docker-compose up`, I get the following error:
```
igest: sha256:2e99c9c97c07066637e243a58727e2f87ede1bf07330c8b17ade94f8147d608f
Status: Downloaded newer image for osgeo/gdal:ubuntu-small-3.2.0
 ---> 2a9ffb4226e6
Step 2/4 : COPY requirements.txt .
COPY failed: file not found in build context or excluded by .dockerignore: stat requirements.txt: file does not exist
ERROR: Service 'srrm' failed to build
```

**Comment by KasimirOr** [comment]
Hi Maze, 
I have updated the readme file as well as the dockerfile & docker-compose.yml

**Comment by maze2point0** [comment]
Awesome, can confirm setup is working. Let's create another issue for the tuple error.
